version: 0.2

environment_variables:
    plaintext:
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - node -v
            - npm -v
    pre_build:
        commands:
            - npm install -g yarn
            - yarn install
    build:
        commands:
            - echo Build started on `date`
            - yarn build
    post_build:
        commands:
            - aws s3 cp build/* s3://steaks-finance --recursive --acl=public-read
            - aws cloudfront create-invalidation --distribution-id E3T7UPTRA0ANBU --paths /index.html
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'build'
    discard-paths: yes
